config/routes.rb
Rails.application.routes.draw do
  root :to => 'airplanes#index'
  resources :users, :only => [:index, :new, :create]
  resources :admins, :only => [:index, :new, :create]
  resources :reservations
  resources :airplanes
  resources :flights
  resources :login
  resources :sessions

  get '/admin/signup' => 'admins#new'
  post '/admin/signup' => 'admins#create'
  get '/current_user', to: 'users#show'


end

app/models/airplane.rb
class Airplane < ApplicationRecord
    has_many :flights
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flight.rb
class Flight < ApplicationRecord
    belongs_to :airplane

    has_many :reservations
    has_many :users, :through => :reservations 

end

app/models/reservation.rb
class Reservation < ApplicationRecord
    belongs_to :user
    belongs_to :flight
end

app/models/user.rb
class User < ApplicationRecord
    has_many :reservations
    has_many :flights, :through => :reservations 
    enum role: [:user, :admin]
      
    def admin?
        role == "admin"
    end
      
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def new
    @admin = User.new
  end

  def create
    @admin = User.new(admin_params)
    @admin.role = "admin"

    if @admin.save
      session[:user_id] = @admin.id # sign in the new admin
      redirect_to new_airplane_path, notice: "Admin account created successfully."
    else
      render :new
    end
  end

  private
  def admin_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/controllers/airplanes_controller.rb
class AirplanesController < ApplicationController
  def index
    @airplanes = Airplane.all
    render json: @airplanes
  end

  def new
      @airplane = Airplane.new
  end

  def create
      # airplane = Airplane.create airplane_params

      data = JSON.parse(request.body.read)
      puts data
      @airplane = Airplane.new(data)
      if @airplane.save
        render json: @airplane, status: :created
      else
        render json: @airplane.errors, status: :unprocessable_entity
      end
    
      # redirect_to airplane
  end

  def edit
      @airplane = Airplane.find params[:id]
  end

  def update
      airplane = Airplane.find params[:id]
      airplane.update airplane_params
      redirect_to airplane
  end

  def show
      @airplane = Airplane.find params[:id]
  end

  def destroy
      airplane = Airplane.find params[:id]
      airplane.destroy
  end

  private

  def airplane_params
      params.require(:airplane).permit(:rows, :column)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    skip_before_action :verify_authenticity_token
    before_action :fetch_user
    skip_before_action :verify_authenticity_token
    
    private
    def fetch_user
        @current_user = User.find_by :id => session[:user_id]
        session[:user_id] = nil unless @current_user.present? # Log out non-existent users.
    end

    def check_for_login
        redirect_to login_path unless @current_user.present?
    end

    def check_for_admin
        redirect_to login_path unless (@current_user.present? && @current_user.admin?)
    end
    
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
    before_action :set_flight, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_admin!, except: [:index, :show]
    
    def index
        @flights = Flight.all
        render json: @flights
    end

    def new
        @flight = Flight.new
    end

    def create
        flight = Flight.create flight_params
        redirect_to flight
    end

    def edit
        @flight = Flight.find params[:id]
    end

    def update
        flight = Flight.find params[:id]
        flight.update flight_params
        redirect_to flight
    end

    def show
        @flight = Flight.find params[:id]
    end

    def destroy
        flight = Flight.find params[:id]
        flight.destroy
        redirect_to flights_path
    end

    private

    def flight_params
        params.require(:flight).permit(:rows, :column)
    end

    def authenticate_admin!
        unless current_user && current_user.admin?
        redirect_to root_path, alert: "You must be an admin to access this page."
        end
    end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    @reservations = Reservation.all
    render json: @reservations
  end

  def new
      @reservation = Reservation.new(user: current_user, seat: @seat)
  end

  def create
    # @flight = Flight.find(params[:flight_id]) # Look for flight records, not sure if params are correct
    # @seat = @flight.seats.find_by(row: params[:row], column: params[:column]) # Look for seat records

    # @reservation = Reservation.new(user: current_user, seat: @seat) # creates new reservation based on current user + seat selection

    data = JSON.parse(request.body.read)
    puts data
    @reservation = Reservation.new(data, user: current_user, seat: @seat)
    if @reservation.save
      render json: @reservation, status: :created
    else
      render json: @reservation.errors, status: :unprocessable_entity
    end

    # redirect_to :root # or wherever the landing page is
  end

  def edit
      @reservation = Reservation.find params[:id]
  end

  def update
      reservation = Reservation.find params[:id]
      reservation.update reservation_params
      redirect_to reservation
  end

  def show
      @reservation = Reservation.find params[:id]
  end

  def destroy
      reservation = Reservation.find params[:id]
      reservation.destroy
      redirect_to reservations_path
  end

  private

  def reservation_params
      params.require(:reservation).permit(:rows, :column)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
  
    def create
      user = User.find_by(username: params[:username])
      if user
        session[:user_id] = user.id
        redirect_to root_path
      else
        flash.now[:alert] = "Invalid username"
        render :new
      end
    end
  
    def destroy
      session[:user_id] = nil
      redirect_to root_path
    end
  end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_for_admin, only: [:index]
  
  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to current_user_path # redirect to the current user page
    else
      render :new
    end
  end

  def show
    @user = current_user
  end
  
  private
  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/airplanes_helper.rb
module AirplanesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/admins/index.html.erb
<h1>All Admins</h1>

<% @admins.each do |admin| %>
  <p><%= admin.username %></p>
<% end %>

app/views/admins/new.html.erb
<h1>Admin Signup</h1>

<% if @admin.errors.any? %>
  <% @admin.errors.full_messages.each do |msg| %>
    <%= msg %>
  <% end %>
<% end %>

<%= form_for @admin do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.submit %>
<% end %>

app/views/airplanes/_form.html.erb
<%= form_for @airplane do |f| %>

    <%= f.label :rows %>
    <%= f.text_field :rows, :required => true %>

    <%= f.label :column %>
    <%= f.text_field :column , :required => true %>

    <%= f.submit %>

<% end %>

app/views/airplanes/edit.html.erb
<%= @airplane.id %>

<%= render :partial => 'form' %>

app/views/airplanes/index.html.erb
<h1>Airplanes</h1>

<%= link_to "New airplane", new_airplane_path %>

<% @airplanes.each do |airplane| %>
    <p><%= link_to airplane.id, airplane  %></p>   
<% end %>

app/views/airplanes/new.html.erb
<h1>New airplane</h1>

<%= render :partial => 'form' %>

app/views/airplanes/show.html.erb
<%= @airplane.id %>

<p>Rows: <%= @airplane.rows %></p>
<p>Column: <%= @airplane.column %></p>

<%= link_to "Edit", edit_airplane_path(@airplane) %>
<%= link_to "Delete", @airplane, :method => :delete %>

app/views/flights/edit.html.erb
<%= @flight.id %>

<%= render :partial => 'form' %>

app/views/flights/index.html.erb
<h1>Flights</h1>

<%= link_to "New flight", new_flight_path %>

<% @flights.each do |flight| %>
    <p><%= link_to flight.id, flight  %></p>   
<% end %>

app/views/flights/new.html.erb
<h1>New plane</h1>

<%= render :partial => 'form' %>

app/views/flights/show.html.erb
<%= @flight.id %>

<p>To: <%= @flight.to %></p>
<p>From: <%= @flight.from %></p>
<p>Date: <%= @flight.date %></p>
<p>Seats: <%= @flight.seats %></p>

<%= link_to "Edit", edit_flight_path(@flight) %>
<%= link_to "Delete", @flight, :method => :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BurningAirlinesServer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reservations/edit.html.erb
<%= @reservation.id %>

<%= render :partial => 'form' %>

app/views/reservations/index.html.erb
<h1>Reservations</h1>

<%= link_to "New reservation", new_reservation_path %>

<% @reservations.each do |reservation| %>
    <p><%= link_to reservation.id, reservation  %></p>   
<% end %>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>

<%= render :partial => 'form' %>

app/views/reservations/show.html.erb
<%= @reservation.id %>

<p>User: <%= @reservation.user_id %></p>
<p>Flight: <%= @reservation.flight_id %></p>

<%= link_to "Edit", edit_reservation_path(@reservation) %>
<%= link_to "Delete", @reservation, :method => :delete %>

app/views/session/new.html.erb
<h1>Login</h1>

<% if flash[:alert] %>
    <%= flash[:alert] %>
<% end %>

<%= form_tag reservaitons_path do %>
    <%= label_tag :username %>
    <%= text_field_tag :username %>

    <%= label_tag :password %>
    <%= password_field_tag :password %>

    <%= submit_tag 'Login' %>
<% end %>

<nav>
  <% if @current_user %>
    <p>Logged in as <%= @current_user.username %></p>
  <% else %>
    <%= link_to "Login", login_path %>
  <% end %>
</nav>

app/views/users/index.html.erb
<h1>All Users</h1>

<% @users.each do |user| %>
  <p><%= user.username %></p>
<% end %>

app/views/users/new.html.erb
<h1>Sign up!</h1>

<% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |msg| %>
      <%= msg %>
    <% end %>
  
<% end %>

<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.submit %>

  <%= link_to "Admin Signup", new_admin_path %>

<% end %>